apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
  namespace: storage
data:
  config.hcl: |-
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_cert_file = "/etc/tls/vault.pem"
      tls_key_file = "/etc/tls/vault-key.pem"
    }
    storage "consul" {
      address = "consul:8500"
      path = "vault/"
      disable_registration = "true"
      ha_enabled = "true"
    }
    seal "awskms" {
      region = "us-east-1"
      kms_key_id = "16e0d961-a791-4054-8046-ac6838434ec9"
    }

    ui = true
