server:
  ha:
    enabled: true

  raft:
    enabled: true

  service:
    enabled: true

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: null
    accessMode: ReadWriteOnce

api_addr: "http://0.0.0.0:8200"
cluster_addr: "https://0.0.0.0:8201"
ui:
  enabled: true
  serviceType: LoadBalancer

