apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: default
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
  annotations:
spec:
  type: LoadBalancer
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 80
      targetPort: 8200
      nodePort: 32000
    - name: https-internal
      port: 443
      targetPort: 8201
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    component: server
